version: '3'
services: 
  web:
    image: zakariae/web
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"
    volumes: 
      - /usr/app/node_modules
      - .:/use/app
  tests:
    image: zakariae/web
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes: 
      - /usr/app/node_modules
      - .:/usr/app
    command: ["npm", "run", "test"]